export  const ADMIN_ROUTE ='/admin'
export  const LOGIN_ROUTE ='/login'
export  const REGISTRATION_ROUTE ='/registration'
export  const COLLECTIONS_ROUTE ='/collections'
export const ITEM_ROUTE ='/item'
export  const COLLECTION_ROUTE ='/collection'